### ISSUE TITLE
osx build issues

### ISSUE THREAD

**Issue by epifanio** [ossimlabs/ossim-planet#1]
Build fails on mac osx 11 (main dependencies installed via homebrew), cmake error log from `build.sh`:

```
[ 81%] Building CXX object ossim-planet/CMakeFiles/ossim-planet.dir/src/ossimPlanet/ossimPlanetElevationDatabase.cpp.o
[ 81%] Building CXX object ossim-planet/CMakeFiles/ossim-planet.dir/src/ossimPlanet/ossimPlanetElevationDatabaseGroup.cpp.o
/Users/epi/dev/ossim/ossim-planet/src/ossimPlanet/ossimPlanetDistanceAccumulator.cpp:244:33: error: no viable conversion from 'const BoundingSphere'
      (aka 'const BoundingSphereImpl<osg::Vec3f>') to 'const osg::BoundingBox' (aka 'const BoundingBoxImpl<osg::Vec3f>')
        const osg::BoundingBox &bb = drawable->getBound();
                                ^    ~~~~~~~~~~~~~~~~~~~~
/usr/local/include/osg/BoundingBox:33:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from
      'const BoundingSphere' (aka 'const BoundingSphereImpl<osg::Vec3f>') to 'const osg::BoundingBoxImpl<osg::Vec3f> &' for 1st argument
class BoundingBoxImpl
      ^
/usr/local/include/osg/BoundingBox:55:16: note: candidate template ignored: could not match 'BoundingBoxImpl' against 'BoundingSphereImpl'
        inline BoundingBoxImpl(const BoundingBoxImpl<BT>& bb) :
               ^
1 error generated.
make[2]: *** [ossim-planet/CMakeFiles/ossim-planet.dir/src/ossimPlanet/ossimPlanetDistanceAccumulator.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [ossim-planet/CMakeFiles/ossim-planet.dir/all] Error 2
make: *** [all] Error 2

Error encountered during make. Check the console log and correct.
```

**Comment by gpotts** [comment]
Hello:

What version are you currently using?   I am currently building to osg 3.2.   I might need to start adding conditional compilation if you are building with a newer version.

Take care

Garrett

**Comment by epifanio** [comment]
Hi @gpotts, I'm using OSG from homebrew which is 

```
osgversion 
OpenSceneGraph Library 3.4.0
```

Thanks a lot for looking into this!

**Comment by gpotts** [comment]
hello:

Could you try an update.  I have modified the dev branch for ossim-planet and it builds on 3.2 and would like to see if it fixes the 3.4.0 build.

Take care

Garrett

**Comment by epifanio** [comment]
@gpotts,

sorry for the huge delay, I'm finally back on this 

I start to build the OSSIM stack From a git master clone
Ossim core built fine, also most of the plugins and ossim-gui.
Now using openscenegraph from homebrew:

```
osgversion 
OpenSceneGraph Library 3.4.0
```

Building ossimplanet I got the following error log, which is different from previous error (I guess is a good sign :) )

```
[ 78%] Building CXX object ossim-planet/CMakeFiles/ossim-planet.dir/src/ossimPlanet/ossimPlanetKmlLayer.cpp.o
In file included from /Users/epi/dev/src/OSSIM_DEV/ossim-planet/src/ossimPlanet/ossimPlanetKmlLayer.cpp:32:
/Users/epi/dev/src/OSSIM_DEV/ossim-planet/include/ossimPlanet/ossimPlanetKmlScreenOverlayNode.h:6:10: fatal error: 
      'osg/CameraNode' file not found
#include <osg/CameraNode>
         ^
1 error generated.
```

Thanks for looking into this.

p.s.
I noticed there is no ossimpanetQt on ossimlabs git repository, will be possible to build it from the svn repository?

**Comment by epifanio** [comment]
reading [here](http://forum.openscenegraph.org/viewtopic.php?t=15133&start=0&postdays=0&postorder=asc&highlight=) I tried to modify

[ossimPlanetKmlScreenOverlayNode.h](https://github.com/ossimlabs/ossim-planet/blob/dev/include/ossimPlanet/ossimPlanetKmlScreenOverlayNode.h#L6)

replacing at [line #6](https://github.com/ossimlabs/ossim-planet/blob/dev/include/ossimPlanet/ossimPlanetKmlScreenOverlayNode.h#L6) from

``` C++
#include <osg/CameraNode>
```

to 

``` C++
#include <osg/Camera>
```

and at [line #24](https://github.com/ossimlabs/ossim-planet/blob/dev/include/ossimPlanet/ossimPlanetKmlScreenOverlayNode.h#L24) from 

``` C++
osg::ref_ptr<osg::Cameranode> theCameraNode;
```

to 

``` C++
osg::ref_ptr<osg::Camera> theCameraNode;
```

Now the build error changed to:

```
Scanning dependencies of target ossim-planet
[ 74%] Building CXX object ossim-planet/CMakeFiles/ossim-planet.dir/src/ossimPlanet/ossimPlanetKmlLayer.cpp.o
[ 74%] Building CXX object ossim-planet/CMakeFiles/ossim-planet.dir/src/ossimPlanet/ossimPlanetKmlLayerNode.cpp.o
[ 74%] Building CXX object ossim-planet/CMakeFiles/ossim-planet.dir/src/ossimPlanet/ossimPlanetKmlNetworkLinkNode.cpp.o
[ 74%] Building CXX object ossim-planet/CMakeFiles/ossim-planet.dir/src/ossimPlanet/ossimPlanetKmlPlacemarkNode.cpp.o
/Users/epi/dev/src/OSSIM_DEV/ossim-planet/src/ossimPlanet/ossimPlanetKmlPlacemarkNode.cpp:506:44: error: no matching constructor for initialization of 'ossimPlanetKmlTextShiftUpdate'
               text->setUpdateCallback(new ossimPlanetKmlTextShiftUpdate(billboardIcon.get(),
                                           ^                             ~~~~~~~~~~~~~~~~~~~~
/Users/epi/dev/src/OSSIM_DEV/ossim-planet/src/ossimPlanet/ossimPlanetKmlPlacemarkNode.cpp:176:4: note: candidate constructor not viable: no known conversion from 'osg::Callback *' to
      'osg::ref_ptr<osg::Drawable::UpdateCallback>' for 3rd argument
   ossimPlanetKmlTextShiftUpdate(ossimPlanetBillboardIcon* icon,
   ^
/Users/epi/dev/src/OSSIM_DEV/ossim-planet/src/ossimPlanet/ossimPlanetKmlPlacemarkNode.cpp:173:7: note: candidate constructor (the implicit copy constructor) not viable: requires 1
      argument, but 3 were provided
class ossimPlanetKmlTextShiftUpdate : public osg::Drawable::UpdateCallback
      ^
1 error generated.
make[2]: *** [ossim-planet/CMakeFiles/ossim-planet.dir/src/ossimPlanet/ossimPlanetKmlPlacemarkNode.cpp.o] Error 1
make[1]: *** [ossim-planet/CMakeFiles/ossim-planet.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by gpotts** [comment]
Hello:

Yea,  I need to go through and update the plane core to support the latest OSG library.  I have not yet upgraded the 3.4 at this time.

We probably need to add a JIRA ticket on our side and get it into the backlog.  Unless,  If you can fork the dev and not the master  branch on ossim-planet and then make the mods if you can find them and then do a pull request that would be great!

I now have the default checkout branch to be dev instead of master if you clone the baseline again.

Take care

Garrett

**Comment by epifanio** [comment]
Thanks @gpotts, I started this https://github.com/ossimlabs/ossim-planet/pull/2
let's see how far I can go. 
Would you like to add ossimlabs on [gitter](https://gitter.im/) ?

**Comment by epifanio** [comment]
@gpotts I'm switching to Ubuntu which has OSG 3.2.3 -- Ossimplanet core builds fine on it. But I have errors in the QT app. I opened a new issue at: https://github.com/ossimlabs/ossim-planet-gui/issues/2

**Comment by epifanio** [comment]
Hi @gpotts @dburken @oscarkramer :) sorry to ping all of you, I miss this :)
After some years, I got my hands on a Mac running an ARM processor. Would you like to use me as a guinea pig for a planet build on this new  platform?

I am using macports to satisfy most of the dependencies,

Cheers!
